<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FiapCloudGames.Contracts" Version="7.0.0" />
    <PackageReference Include="FiapCloudGames.RabbitMq" Version="1.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CatalogAPI.Domain\CatalogAPI.Domain.csproj" />
    <ProjectReference Include="..\CatalogAPI.Application\CatalogAPI.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contexts\" />
  </ItemGroup>

</Project>
